server:
  port: 8888

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/identity/**
