server:
  port: 8888

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/identity/**

            - id: profile-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/profile/**

            - id: chat-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/chat/**

            - id: assignment-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/assignments/**

            - id: classroom-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/classrooms/**

            - id: search-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/searches/**

            - id: question-service
              uri: http://localhost:8086
              predicates:
                - Path=/api/questions/**

            - id: post-service
              uri: http://localhost:8087
              predicates:
                - Path=/api/post/**