server:
  port: 8888

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/identity/**

            - id: profile-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/profile/**

            - id: assignment-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/assignments/**