server:
  port: 8083
  servlet:
    context-path: /api/assignments

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/assignment_service"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cloudinary:
  cloud:
    name: dvnqcio6h
  api:
    key: 511958648376181
    secret: l9KYs3TXQIGMZaZkwuktyWmLEUQ
  folder: assignment-submissions