server:
  port: 8083
  servlet:
    context-path: /api/assignments

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/assignment_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
