server:
  port: 8088
  servlet:
    context-path: /api/score

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/score_service"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  services:
    profile: http://localhost:8081/api/profile
    identity: http://localhost:8080/api/identity

