server:
  port: 8081
  servlet:
    context-path: /api/profile

spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678

app:
  services:
    identity: http://localhost:8080/api/identity

cloudinary:
  cloud-name: dacaq64o6
  api-key: 437197883379755
  api-secret: HV7alb6Clh4OJJXIoqKy4eWxF40